version: "3.4"

networks:
  db_net:
    external: true
  default:

services:
  core:
    env_file:
      - .env
    container_name: core
    depends_on:
      - redis
      - postgres
    build:
      context: ""
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/opt/app
    tmpfs:
      - /var/excel/:exec,size=500m
    networks:
      - default
    restart: unless-stopped
  redis:
    restart: unless-stopped
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./.docker_data/redis:/redis/data
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - db_net
      - default
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data